# Use a lightweight Python base image
FROM python:3.12

# Set working directory
WORKDIR /app

# Copy all files from your current directory into the container's working directory
COPY . .

# Install required libraries
RUN pip install -r requirements.txt