services:
  chromadb:
    image: chromadb/chroma
    hostname: chromadb
    volumes:
      - chromadb_data:/chroma/chroma
    ports:
      - 8000:8000
    profiles: ["test","develop","prod"]
      
  rag-llm:
    build: 
      .
    ports:
      - "5000:5000"
    volumes:
      - rag_llm_data:/app
    env_file:
      - env-file.txt
    depends_on:
      - chromadb
    profiles: ["develop","prod"]

  test-rag-llm:
    build: 
      dockerfile: DockerfileTest
    env_file:
      - env-file.txt
    volumes:
      - ./coverage:/app/htmlcov 
    depends_on:
      - chromadb
    profiles: ["test"]

volumes:
  chromadb_data:
    driver: local
  rag_llm_data:
    driver: local