# Use the base image
FROM base_image

# Set working directory
WORKDIR /app

# Copy all files from your current directory into the container's working directory
COPY . .

# Entry point command
CMD [ "python", "src/main.py"]
