name: Java CI with Maven

on:
  push:
    branches-ignore: []
  pull_request:
    branches-ignore: []

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('fitnessWebApp/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn -B package --file fitnessWebApp/pom.xml
    - name: Test with Maven
      run: mvn test --file fitnessWebApp/pom.xml
    - name: Generate Code Coverage Report
      run: mvn jacoco:report --file fitnessWebApp/pom.xml
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./fitnessWebApp/target/site/jacoco/jacoco.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
